menu:
# - {name: 'people', url: '/people'}
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

# people:
# - {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
# - {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
# - {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/Echotengli'}
- {icon: 'twitter', link: 'https://x.com/echo70084382'}
- {icon: 'instagram', link: 'https://www.instagram.com/echo_teng_li'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/echo-teng-li-b846a7231'}

contacts:
- {name: 'Teng Li', title: 'PhD student', department: 'Faculty of Behavioural and Social Sciences', institution: 'University of Groningen', institution_address: 'Grote Kruisstraat 2/1, 9712 TS Groningen, The Netherlands', phone: '(+31) 503637623', email: 'teng.li@rug.nl', office: 'B.119', image: 'assets/img/contact.jpg'}
